name: Lint

on:
  pull_request:
    paths:
      - '.github/workflows/*.yml'

jobs:
  actionlint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: actionlint
      uses: reviewdog/action-actionlint@v1
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
        level: warning
