name: Make download count badges from App Store

on:
  schedule:
    - cron: '0 3 4 * *' # Run at 3:00 AM on the 4th of every month
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-24.04

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

    - name: Create config.yml
      env:
        CONFIG_YML: ${{ secrets.CONFIG_YML }}
      run: echo "$CONFIG_YML" > config.yml
    
    - name: Create private key
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      run: echo "$PRIVATE_KEY" > private.p8

    - name: Setup Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
      with:
        python-version: '3.14'
        cache: 'pip'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Generate badges
      run: |
        app-store-download-count-badge-maker generate
        ls dist/

    - name: Create index.html
      run: app-store-download-count-badge-maker make-index

    - name: Setup Pages
      uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d  # v6.0.0

    - name: Upload artifacts
      uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9  # v5.0.0
      with:
        path: './dist'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346  # v5.0.1
